version: '2'

services:
  redcap:
    restart: always
    build:
      context: ./redcap
      args:
        redcap_version: "6.15.1"
    ports:
      - "80:80"
    volumes:
      - /share:/share
    network_mode: host

