version: '2'

services:
  redcap:
    restart: always
    build:
      context: ./redcap
      args:
        redcap_version: "7.4.4"
    ports:
      - "80:80"
    volumes:
      - /share:/share
    network_mode: host

